# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 854e9aed263bd748339596e586f3eee40af4f554d3629c4eb710a2cd223885c307ce677fb11e8b1037be7bbb0a054b4243390e7f2c62aa0a50801edbedc5158a

test:
  secret_key_base: fdcc761534b2cac6efdf2e89744eef12f6a7a1830c5851a26899e169c89f61c8932ee7e8e59cffc46fcc620dedaa4fe96ddae923718fe9a511d7d580b7c4248d

# Do not keep production secrets in the repository,
# instead read values from the environment.
# ^ There is no session data so...
production:
  secret_key_base: fdcc761534b2cac6efdf2e89744eef12f6a7a1830c5851a26899e169c89f61c8932ee7e8e59cffc46fcc620dedaa4fe96ddae923718fe9a511d7d580b7c4248d
  secret_token: fdcc761534b2cac6efdd2e89744eef12f6a7a1830c5851a26899e169c89f61c8932ee7e8e59cffc46fcc620dedaa4fe96ddae923718fe9a511d7d580b7c4248d
